pool: Build
name: Production - 8I516 AF
trigger: none

variables:
  - group: "WebDeploy PRODUCTION"  

stages:
  - template: ./template.yml
    parameters:
      azureSubscription: $(subscription)
      afs: 
        - afName: socpro-support-8i516-we-af
          afDisplayName: 8I516 WE
     
      afsNE:
        - afName: socpro-support-8i516-ne-af
          afDisplayName: 8I516 NE

      projectName: AF.PerfIssues.Samples.Net8Isolated516