pool: Build
name: Production - 8I511 AF
trigger: none

variables:
  - group: "WebDeploy PRODUCTION"  

stages:
  - template: ../template.yml
    parameters:
      azureSubscription: $(subscription)
      afs: 
        - afName: socpro-support-8i511-we-af
          afDisplayName: 8I511 WE
     
      afsNE:
        - afName: socpro-support-8i511-ne-af
          afDisplayName: 8I511 NE

      projectName: AF.PerfIssues.Samples.Net8Isolated511