pool: Build
name: Production - 8P511 AF
trigger: none

variables:
  - group: "WebDeploy PRODUCTION"  

stages:
  - template: ./template.yml
    parameters:
      azureSubscription: $(subscription)
      afs: 
        - afName: socpro-support-8p511-we-af
          afDisplayName: 8P511 WE
     
      afsNE:
        - afName: socpro-support-8p511-ne-af
          afDisplayName: 8P511 NE

      projectName: AF.PerfIssues.Samples.Net8InProc511