pool: Build
name: Production - 8P512 AF
trigger: none

variables:
  - group: "WebDeploy PRODUCTION"  

stages:
  - template: ./template.yml
    parameters:
      azureSubscription: $(subscription)
      afs: 
        - afName: socpro-support-8p512-we-af
          afDisplayName: 8P512 WE
     
      afsNE:
        - afName: socpro-support-8p512-ne-af
          afDisplayName: 8P512 NE

      projectName: AF.PerfIssues.Samples.Net8InProc512